/* eslint-disable @next/next/no-img-element */
import Link from 'next/link'
import { requireAdmin } from '@/lib/admin-auth'
import { getAdminTvVideos, getTvOptions, TvFilter } from '@/lib/admin-tv'
import { videoState, youtubeThumbnail } from '@/lib/admin-tv-shared'

const filters: { value: TvFilter; label: string }[] = [{value:'all',label:'All'},{value:'public',label:'Public'},{value:'scheduled',label:'Scheduled'},{value:'hidden',label:'Hidden'},{value:'featured',label:'Featured'}]
const fmt = (value: string | null) => value ? new Intl.DateTimeFormat('en', { dateStyle:'medium', timeStyle:'short' }).format(new Date(value)) : 'Immediately'
export default async function AdminTvPage({ searchParams }: { searchParams: Promise<{ status?: string; category?: string }> }) {
  await requireAdmin(); const params = await searchParams
  const status = filters.some(x => x.value === params.status) ? params.status as TvFilter : 'all'
  const options = await getTvOptions(); const validCategory = options.categories.some(x => x.id === params.category) ? params.category : undefined
  const result = await getAdminTvVideos(status, validCategory)
  const href = (filter: TvFilter, category = validCategory) => `/admin/tv?${new URLSearchParams(Object.fromEntries([filter !== 'all' ? ['status',filter] : null, category ? ['category',category] : null].filter(Boolean) as [string,string][]))}`
  return <section><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Publishing</p><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Evo TV</h1><p className="mt-3 text-zinc-400">Manage videos, schedules, and series.</p></div><div className="flex gap-3"><Link href="/admin/tv/series" className="button-secondary px-5 py-3 text-sm font-bold">Manage series</Link><Link href="/admin/tv/new" className="button-primary px-5 py-3 text-sm">New video</Link></div></div>
    <nav aria-label="Filter videos" className="admin-filter-nav mt-8 flex gap-2 overflow-x-auto border-b border-white/10 pb-4">{filters.map(x => <Link key={x.value} href={href(x.value)} aria-current={status === x.value ? 'page' : undefined} className="min-w-max px-4 py-2 text-xs uppercase tracking-wider">{x.label}</Link>)}</nav>
    <form className="mt-5 flex flex-wrap items-end gap-3"><label className="text-xs font-bold uppercase tracking-wider text-zinc-400">Category<select name="category" defaultValue={validCategory ?? ''} className="ml-3 border border-white/15 bg-zinc-950 px-3 py-2 text-sm normal-case text-white"><option value="">All categories</option>{options.categories.map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{status !== 'all' && <input type="hidden" name="status" value={status} />}<button className="button-secondary px-3 py-2 text-sm font-bold">Apply</button></form>
    {result.hasError && <p role="alert" className="mt-7 border border-rose-400/30 p-5 text-rose-200">Videos could not be fully loaded.</p>}
    {!result.hasError && !result.videos.length && <div className="mt-7 grid min-h-64 place-items-center border border-dashed border-white/15 text-center"><div><h2 className="text-2xl font-semibold">No videos match this view.</h2><Link href="/admin/tv/new" className="button-primary mt-5 px-5 py-3 text-sm">Add a video</Link></div></div>}
    {!!result.videos.length && <ul className="mt-7 divide-y divide-white/10 border border-white/10">{result.videos.map(video => { const state = videoState(video); return <li key={video.id} className="grid gap-5 bg-zinc-950/40 p-5 md:grid-cols-[10rem_minmax(12rem,2fr)_1fr_1fr_auto] md:items-center"><img src={youtubeThumbnail(video)} alt="" className="aspect-video w-full object-cover" /><div className="min-w-0"><h2 className="truncate font-semibold">{video.title}</h2><p className="mt-1 truncate text-xs text-zinc-500">{video.youtube_video_id} · /{video.slug}</p><div className="mt-3 flex gap-2"><span className={`border px-2 py-1 text-[.65rem] font-bold uppercase ${state === 'public' ? 'border-emerald-400/30 text-emerald-300' : state === 'scheduled' ? 'border-sky-400/30 text-sky-300' : 'border-white/20 text-zinc-300'}`}>{state}</span>{video.featured && <span className="border border-amber-300/30 px-2 py-1 text-[.65rem] font-bold uppercase text-amber-300">Featured</span>}</div></div><div className="text-sm text-zinc-300"><p>{video.category_id ? result.categories.get(video.category_id) ?? 'Unknown category' : 'Uncategorized'}</p><p className="mt-1 text-zinc-500">{video.series_id ? result.series.get(video.series_id) ?? 'Unknown series' : 'No series'}</p></div><p className="text-xs text-zinc-400"><span className="md:hidden">Publication: </span>{fmt(video.published_at)}</p><div className="flex gap-4"><Link href={`/admin/tv/${video.id}/preview`} className="text-sm font-bold text-zinc-200">Preview</Link><Link href={`/admin/tv/${video.id}/edit`} className="text-sm font-bold text-amber-300">Edit</Link></div></li>})}</ul>}
  </section>
}
