/* eslint-disable @next/next/no-img-element */
import Link from 'next/link'
import { requireAdmin } from '@/lib/admin-auth'
import { getVaultProducts } from '@/lib/admin-vault'

const money = (value: number | string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value))
export default async function VaultProductsPage() {
  await requireAdmin(); const result = await getVaultProducts()
  return <section><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Evo Vault</p><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Products</h1><p className="mt-3 text-zinc-400">Books and courses in deterministic catalog order.</p></div><div className="flex gap-3"><Link href="/admin/vault" className="button-secondary px-5 py-3 text-sm font-bold">Overview</Link><Link href="/admin/vault/products/new" className="button-primary px-5 py-3 text-sm">Add product</Link></div></div>
    {result.hasError && <p role="alert" className="mt-7 border border-rose-400/30 p-5 text-rose-200">Products could not be loaded.</p>}
    {!result.hasError && !result.products.length && <div className="mt-7 grid min-h-64 place-items-center border border-dashed border-white/15 text-center"><div><h2 className="text-2xl font-semibold">No Vault products yet.</h2><Link href="/admin/vault/products/new" className="button-primary mt-5 px-5 py-3 text-sm">Add a product</Link></div></div>}
    {!!result.products.length && <ul className="mt-7 divide-y divide-white/10 border border-white/10">{result.products.map(product => <li key={product.id} className="grid gap-5 bg-zinc-950/40 p-5 sm:grid-cols-[5rem_minmax(12rem,2fr)_1fr_1fr_auto] sm:items-center">{product.cover_image_url ? <img src={product.cover_image_url} alt="" className="aspect-[3/4] w-20 object-cover" /> : <div className="grid aspect-[3/4] w-20 place-items-center border border-white/10 bg-black/30 text-[.6rem] uppercase tracking-wider text-zinc-600">No cover</div>}<div className="min-w-0"><h2 className="truncate font-semibold">{product.name}</h2><p className="mt-1 truncate text-xs text-zinc-500">/{product.slug}</p><div className="mt-3 flex flex-wrap gap-2"><span className="border border-amber-300/30 px-2 py-1 text-[.65rem] font-bold uppercase text-amber-300">{product.kind}</span><span className={`border px-2 py-1 text-[.65rem] font-bold uppercase ${product.is_active ? 'border-emerald-400/30 text-emerald-300' : 'border-white/20 text-zinc-400'}`}>{product.is_active ? 'Active' : 'Inactive'}</span>{product.is_featured && <span className="border border-amber-300/30 px-2 py-1 text-[.65rem] font-bold uppercase text-amber-300">Featured</span>}</div></div><p className="text-sm capitalize text-zinc-300">{product.product_mode}</p><p className="text-sm font-semibold tabular-nums">{money(product.price)}</p><Link href={`/admin/vault/products/${product.id}/edit`} className="text-sm font-bold text-amber-300">Edit</Link></li>)}</ul>}
  </section>
}
