BEGIN;
SET LOCAL search_path = public, extensions;
SELECT no_plan();
SELECT has_table('public','evo_store_checkouts','evo_store_checkouts exists');
SELECT columns_are('public','evo_store_checkouts',ARRAY['id','user_id','idempotency_key','request_fingerprint','status','currency','subtotal','discount_total','shipping_total','tax_total','grand_total','address_id','shipping_full_name','shipping_phone','shipping_address_line1','shipping_address_line2','shipping_landmark','shipping_city','shipping_state','shipping_postal_code','shipping_country','created_at','updated_at','expires_at','released_at','expired_at','consumed_at']);
SELECT col_is_pk('public','evo_store_checkouts','id','evo_store_checkouts.id col_is_pk');
SELECT col_type_is('public','evo_store_checkouts','id','uuid','evo_store_checkouts.id col_type_is');
SELECT col_not_null('public','evo_store_checkouts','id','evo_store_checkouts.id col_not_null');
SELECT col_type_is('public','evo_store_checkouts','user_id','uuid','evo_store_checkouts.user_id col_type_is');
SELECT col_not_null('public','evo_store_checkouts','user_id','evo_store_checkouts.user_id col_not_null');
SELECT col_type_is('public','evo_store_checkouts','idempotency_key','uuid','evo_store_checkouts.idempotency_key col_type_is');
SELECT col_not_null('public','evo_store_checkouts','idempotency_key','evo_store_checkouts.idempotency_key col_not_null');
SELECT col_type_is('public','evo_store_checkouts','request_fingerprint','text','evo_store_checkouts.request_fingerprint col_type_is');
SELECT col_not_null('public','evo_store_checkouts','request_fingerprint','evo_store_checkouts.request_fingerprint col_not_null');
SELECT col_type_is('public','evo_store_checkouts','status','evo_store_checkout_status','evo_store_checkouts.status col_type_is');
SELECT col_not_null('public','evo_store_checkouts','status','evo_store_checkouts.status col_not_null');
SELECT col_type_is('public','evo_store_checkouts','currency','character(3)','evo_store_checkouts.currency col_type_is');
SELECT col_not_null('public','evo_store_checkouts','currency','evo_store_checkouts.currency col_not_null');
SELECT col_type_is('public','evo_store_checkouts','subtotal','numeric(14,2)','evo_store_checkouts.subtotal col_type_is');
SELECT col_not_null('public','evo_store_checkouts','subtotal','evo_store_checkouts.subtotal col_not_null');
SELECT col_type_is('public','evo_store_checkouts','discount_total','numeric(14,2)','evo_store_checkouts.discount_total col_type_is');
SELECT col_not_null('public','evo_store_checkouts','discount_total','evo_store_checkouts.discount_total col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_total','numeric(14,2)','evo_store_checkouts.shipping_total col_type_is');
SELECT col_is_null('public','evo_store_checkouts','shipping_total','evo_store_checkouts.shipping_total col_is_null');
SELECT col_type_is('public','evo_store_checkouts','tax_total','numeric(14,2)','evo_store_checkouts.tax_total col_type_is');
SELECT col_is_null('public','evo_store_checkouts','tax_total','evo_store_checkouts.tax_total col_is_null');
SELECT col_type_is('public','evo_store_checkouts','grand_total','numeric(14,2)','evo_store_checkouts.grand_total col_type_is');
SELECT col_is_null('public','evo_store_checkouts','grand_total','evo_store_checkouts.grand_total col_is_null');
SELECT col_type_is('public','evo_store_checkouts','address_id','uuid','evo_store_checkouts.address_id col_type_is');
SELECT col_is_null('public','evo_store_checkouts','address_id','evo_store_checkouts.address_id col_is_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_full_name','text','evo_store_checkouts.shipping_full_name col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_full_name','evo_store_checkouts.shipping_full_name col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_phone','text','evo_store_checkouts.shipping_phone col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_phone','evo_store_checkouts.shipping_phone col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_address_line1','text','evo_store_checkouts.shipping_address_line1 col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_address_line1','evo_store_checkouts.shipping_address_line1 col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_address_line2','text','evo_store_checkouts.shipping_address_line2 col_type_is');
SELECT col_is_null('public','evo_store_checkouts','shipping_address_line2','evo_store_checkouts.shipping_address_line2 col_is_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_landmark','text','evo_store_checkouts.shipping_landmark col_type_is');
SELECT col_is_null('public','evo_store_checkouts','shipping_landmark','evo_store_checkouts.shipping_landmark col_is_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_city','text','evo_store_checkouts.shipping_city col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_city','evo_store_checkouts.shipping_city col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_state','text','evo_store_checkouts.shipping_state col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_state','evo_store_checkouts.shipping_state col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_postal_code','text','evo_store_checkouts.shipping_postal_code col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_postal_code','evo_store_checkouts.shipping_postal_code col_not_null');
SELECT col_type_is('public','evo_store_checkouts','shipping_country','text','evo_store_checkouts.shipping_country col_type_is');
SELECT col_not_null('public','evo_store_checkouts','shipping_country','evo_store_checkouts.shipping_country col_not_null');
SELECT col_type_is('public','evo_store_checkouts','created_at','timestamp with time zone','evo_store_checkouts.created_at col_type_is');
SELECT col_not_null('public','evo_store_checkouts','created_at','evo_store_checkouts.created_at col_not_null');
SELECT col_type_is('public','evo_store_checkouts','updated_at','timestamp with time zone','evo_store_checkouts.updated_at col_type_is');
SELECT col_not_null('public','evo_store_checkouts','updated_at','evo_store_checkouts.updated_at col_not_null');
SELECT col_type_is('public','evo_store_checkouts','expires_at','timestamp with time zone','evo_store_checkouts.expires_at col_type_is');
SELECT col_not_null('public','evo_store_checkouts','expires_at','evo_store_checkouts.expires_at col_not_null');
SELECT col_type_is('public','evo_store_checkouts','released_at','timestamp with time zone','evo_store_checkouts.released_at col_type_is');
SELECT col_is_null('public','evo_store_checkouts','released_at','evo_store_checkouts.released_at col_is_null');
SELECT col_type_is('public','evo_store_checkouts','expired_at','timestamp with time zone','evo_store_checkouts.expired_at col_type_is');
SELECT col_is_null('public','evo_store_checkouts','expired_at','evo_store_checkouts.expired_at col_is_null');
SELECT col_type_is('public','evo_store_checkouts','consumed_at','timestamp with time zone','evo_store_checkouts.consumed_at col_type_is');
SELECT col_is_null('public','evo_store_checkouts','consumed_at','evo_store_checkouts.consumed_at col_is_null');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.evo_store_checkouts'::regclass),'evo_store_checkouts RLS enabled');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','SELECT'),'anon has no SELECT on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','INSERT'),'anon has no INSERT on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','UPDATE'),'anon has no UPDATE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','DELETE'),'anon has no DELETE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','TRUNCATE'),'anon has no TRUNCATE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','REFERENCES'),'anon has no REFERENCES on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkouts','TRIGGER'),'anon has no TRIGGER on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','INSERT'),'authenticated has no INSERT on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','UPDATE'),'authenticated has no UPDATE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','DELETE'),'authenticated has no DELETE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','TRUNCATE'),'authenticated has no TRUNCATE on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','REFERENCES'),'authenticated has no REFERENCES on evo_store_checkouts');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkouts','TRIGGER'),'authenticated has no TRIGGER on evo_store_checkouts');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkouts','SELECT'),'evo_store_checkouts service SELECT privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkouts','INSERT'),'evo_store_checkouts service INSERT privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkouts','UPDATE'),'evo_store_checkouts service UPDATE privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkouts','DELETE'),'evo_store_checkouts service DELETE privilege');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_class c CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE c.oid='public.evo_store_checkouts'::regclass AND a.grantee=0),'evo_store_checkouts no PUBLIC ACL');
SELECT has_table('public','evo_store_checkout_items','evo_store_checkout_items exists');
SELECT columns_are('public','evo_store_checkout_items',ARRAY['id','checkout_id','variant_id','product_id','quantity','currency','unit_price','line_subtotal','product_name','variant_name','sku','size_code','color_code']);
SELECT col_is_pk('public','evo_store_checkout_items','id','evo_store_checkout_items.id col_is_pk');
SELECT col_type_is('public','evo_store_checkout_items','id','uuid','evo_store_checkout_items.id col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','id','evo_store_checkout_items.id col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','checkout_id','uuid','evo_store_checkout_items.checkout_id col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','checkout_id','evo_store_checkout_items.checkout_id col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','variant_id','uuid','evo_store_checkout_items.variant_id col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','variant_id','evo_store_checkout_items.variant_id col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','product_id','uuid','evo_store_checkout_items.product_id col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','product_id','evo_store_checkout_items.product_id col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','quantity','integer','evo_store_checkout_items.quantity col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','quantity','evo_store_checkout_items.quantity col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','currency','character(3)','evo_store_checkout_items.currency col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','currency','evo_store_checkout_items.currency col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','unit_price','numeric(14,2)','evo_store_checkout_items.unit_price col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','unit_price','evo_store_checkout_items.unit_price col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','line_subtotal','numeric(14,2)','evo_store_checkout_items.line_subtotal col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','line_subtotal','evo_store_checkout_items.line_subtotal col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','product_name','text','evo_store_checkout_items.product_name col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','product_name','evo_store_checkout_items.product_name col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','variant_name','text','evo_store_checkout_items.variant_name col_type_is');
SELECT col_is_null('public','evo_store_checkout_items','variant_name','evo_store_checkout_items.variant_name col_is_null');
SELECT col_type_is('public','evo_store_checkout_items','sku','text','evo_store_checkout_items.sku col_type_is');
SELECT col_not_null('public','evo_store_checkout_items','sku','evo_store_checkout_items.sku col_not_null');
SELECT col_type_is('public','evo_store_checkout_items','size_code','text','evo_store_checkout_items.size_code col_type_is');
SELECT col_is_null('public','evo_store_checkout_items','size_code','evo_store_checkout_items.size_code col_is_null');
SELECT col_type_is('public','evo_store_checkout_items','color_code','text','evo_store_checkout_items.color_code col_type_is');
SELECT col_is_null('public','evo_store_checkout_items','color_code','evo_store_checkout_items.color_code col_is_null');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.evo_store_checkout_items'::regclass),'evo_store_checkout_items RLS enabled');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','SELECT'),'anon has no SELECT on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','INSERT'),'anon has no INSERT on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','UPDATE'),'anon has no UPDATE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','DELETE'),'anon has no DELETE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','TRUNCATE'),'anon has no TRUNCATE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','REFERENCES'),'anon has no REFERENCES on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('anon','public.evo_store_checkout_items','TRIGGER'),'anon has no TRIGGER on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','INSERT'),'authenticated has no INSERT on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','UPDATE'),'authenticated has no UPDATE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','DELETE'),'authenticated has no DELETE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','TRUNCATE'),'authenticated has no TRUNCATE on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','REFERENCES'),'authenticated has no REFERENCES on evo_store_checkout_items');
SELECT ok(NOT has_table_privilege('authenticated','public.evo_store_checkout_items','TRIGGER'),'authenticated has no TRIGGER on evo_store_checkout_items');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkout_items','SELECT'),'evo_store_checkout_items service SELECT privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkout_items','INSERT'),'evo_store_checkout_items service INSERT privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkout_items','UPDATE'),'evo_store_checkout_items service UPDATE privilege');
SELECT ok(has_table_privilege('service_role','public.evo_store_checkout_items','DELETE'),'evo_store_checkout_items service DELETE privilege');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_class c CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE c.oid='public.evo_store_checkout_items'::regclass AND a.grantee=0),'evo_store_checkout_items no PUBLIC ACL');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkouts'::regclass AND conname='evo_store_checkouts_user_idempotency_key'),'UNIQUE (user_id, idempotency_key)','evo_store_checkouts_user_idempotency_key');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkouts'::regclass AND conname='evo_store_checkouts_id_currency_key'),'UNIQUE (id, currency)','evo_store_checkouts_id_currency_key');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkouts'::regclass AND conname='evo_store_checkouts_user_id_fkey'),'FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT','evo_store_checkouts_user_id_fkey');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkouts'::regclass AND conname='evo_store_checkouts_address_id_fkey'),'FOREIGN KEY (address_id) REFERENCES addresses(id) ON DELETE SET NULL','evo_store_checkouts_address_id_fkey');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkout_items'::regclass AND conname='evo_store_checkout_items_checkout_currency_fkey'),'FOREIGN KEY (checkout_id, currency) REFERENCES evo_store_checkouts(id, currency) ON UPDATE RESTRICT ON DELETE RESTRICT','evo_store_checkout_items_checkout_currency_fkey');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkout_items'::regclass AND conname='evo_store_checkout_items_variant_id_fkey'),'FOREIGN KEY (variant_id) REFERENCES evo_store_variants(id) ON DELETE RESTRICT','evo_store_checkout_items_variant_id_fkey');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkout_items'::regclass AND conname='evo_store_checkout_items_product_id_fkey'),'FOREIGN KEY (product_id) REFERENCES evo_store_products(id) ON DELETE RESTRICT','evo_store_checkout_items_product_id_fkey');
SELECT is((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.evo_store_checkout_items'::regclass AND conname='evo_store_checkout_items_checkout_variant_key'),'UNIQUE (checkout_id, variant_id)','evo_store_checkout_items_checkout_variant_key');
SELECT ok(position('(user_id)' in pg_get_indexdef('public.evo_store_checkouts_one_active_user_idx'::regclass)) > 0,'evo_store_checkouts_one_active_user_idx key order');
SELECT ok((SELECT indisunique = true AND indpred IS NOT NULL FROM pg_index WHERE indexrelid='public.evo_store_checkouts_one_active_user_idx'::regclass),'evo_store_checkouts_one_active_user_idx uniqueness/predicate');
SELECT ok((SELECT pg_get_expr(indpred,indrelid) = '(status = ''active''::evo_store_checkout_status)' FROM pg_index WHERE indexrelid='public.evo_store_checkouts_one_active_user_idx'::regclass),'evo_store_checkouts_one_active_user_idx only active');
SELECT ok(position('(expires_at, id)' in pg_get_indexdef('public.evo_store_checkouts_active_expiry_idx'::regclass)) > 0,'evo_store_checkouts_active_expiry_idx key order');
SELECT ok((SELECT indisunique = false AND indpred IS NOT NULL FROM pg_index WHERE indexrelid='public.evo_store_checkouts_active_expiry_idx'::regclass),'evo_store_checkouts_active_expiry_idx uniqueness/predicate');
SELECT ok((SELECT pg_get_expr(indpred,indrelid) = '(status = ''active''::evo_store_checkout_status)' FROM pg_index WHERE indexrelid='public.evo_store_checkouts_active_expiry_idx'::regclass),'evo_store_checkouts_active_expiry_idx only active');
SELECT ok(position('(user_id, created_at DESC, id DESC)' in pg_get_indexdef('public.evo_store_checkouts_user_history_idx'::regclass)) > 0,'evo_store_checkouts_user_history_idx key order');
SELECT ok((SELECT indisunique = false AND indpred IS NULL FROM pg_index WHERE indexrelid='public.evo_store_checkouts_user_history_idx'::regclass),'evo_store_checkouts_user_history_idx uniqueness/predicate');
SELECT ok(position('(checkout_id, id)' in pg_get_indexdef('public.evo_store_checkout_items_checkout_order_idx'::regclass)) > 0,'evo_store_checkout_items_checkout_order_idx key order');
SELECT ok((SELECT indisunique = false AND indpred IS NULL FROM pg_index WHERE indexrelid='public.evo_store_checkout_items_checkout_order_idx'::regclass),'evo_store_checkout_items_checkout_order_idx uniqueness/predicate');
SELECT ok(position('(variant_id, checkout_id)' in pg_get_indexdef('public.evo_store_checkout_items_variant_checkout_idx'::regclass)) > 0,'evo_store_checkout_items_variant_checkout_idx key order');
SELECT ok((SELECT indisunique = false AND indpred IS NULL FROM pg_index WHERE indexrelid='public.evo_store_checkout_items_variant_checkout_idx'::regclass),'evo_store_checkout_items_variant_checkout_idx uniqueness/predicate');
SELECT is(enum_range(NULL::public.evo_store_checkout_status)::text,'{active,released,expired,consumed}','exact lifecycle');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_attrdef d JOIN pg_attribute a ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE d.adrelid='public.evo_store_checkouts'::regclass AND a.attname='shipping_total'),'shipping_total no default');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_attrdef d JOIN pg_attribute a ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE d.adrelid='public.evo_store_checkouts'::regclass AND a.attname='tax_total'),'tax_total no default');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_attrdef d JOIN pg_attribute a ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE d.adrelid='public.evo_store_checkouts'::regclass AND a.attname='grand_total'),'grand_total no default');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_attrdef d JOIN pg_attribute a ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE d.adrelid='public.evo_store_checkouts'::regclass AND a.attname='expires_at'),'expires_at no default');
SELECT ok((SELECT pg_get_constraintdef(oid) LIKE '%private.evo_store_currency_supported%' FROM pg_constraint WHERE conrelid='public.evo_store_checkouts'::regclass AND conname='evo_store_checkouts_currency_supported_check'),'evo_store_checkouts shares one currency authority');
SELECT ok((SELECT pg_get_constraintdef(oid) LIKE '%private.evo_store_currency_supported%' FROM pg_constraint WHERE conrelid='public.evo_store_checkout_items'::regclass AND conname='evo_store_checkout_items_currency_supported_check'),'evo_store_checkout_items shares one currency authority');
SELECT ok((SELECT pg_get_constraintdef(oid) LIKE '%private.evo_store_currency_supported%' FROM pg_constraint WHERE conrelid='public.evo_store_variant_prices'::regclass AND conname='evo_store_variant_prices_currency_supported_check'),'evo_store_variant_prices shares one currency authority');
SELECT ok((SELECT NOT prosecdef AND provolatile='i' AND proisstrict AND proconfig=ARRAY['search_path=""'] FROM pg_proc WHERE oid='private.evo_store_currency_supported(text)'::regprocedure),'currency helper is immutable strict invoker with empty search path');
SELECT ok(NOT has_function_privilege('anon','private.evo_store_currency_supported(text)','EXECUTE'),'anonymous cannot call private currency helper');
SELECT ok(NOT has_function_privilege('authenticated','private.guard_evo_store_checkout_terminal_status()','EXECUTE'),'customers cannot call lifecycle guard');
SELECT ok((SELECT NOT prosecdef AND proconfig=ARRAY['search_path=""'] FROM pg_proc WHERE oid='private.guard_evo_store_checkout_terminal_status()'::regprocedure),'terminal guard is hardened invoker');
SELECT ok(private.evo_store_currency_supported('USD'),'USD is supported');
SELECT ok(private.evo_store_currency_supported('EUR'),'EUR is supported');
SELECT ok(private.evo_store_currency_supported('GBP'),'GBP is supported');
SELECT ok(private.evo_store_currency_supported('INR'),'INR is supported');
SELECT ok(private.evo_store_currency_supported('CAD'),'CAD is supported');
SELECT ok(private.evo_store_currency_supported('AUD'),'AUD is supported');
SELECT ok(private.evo_store_currency_supported('NZD'),'NZD is supported');
SELECT ok(private.evo_store_currency_supported('SGD'),'SGD is supported');
SELECT ok(private.evo_store_currency_supported('AED'),'AED is supported');
SELECT ok(private.evo_store_currency_supported('JPY'),'JPY is supported');
SELECT ok(NOT private.evo_store_currency_supported('XYZ'),'unsupported currency rejected');
-- Test-only helpers, rolled back; no application RPCs.
CREATE FUNCTION pg_temp.checkout(p_user uuid, p_key uuid DEFAULT gen_random_uuid(), p_status public.evo_store_checkout_status DEFAULT 'active')
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE result uuid;
BEGIN
 INSERT INTO public.evo_store_checkouts(user_id,idempotency_key,request_fingerprint,status,currency,subtotal,
 shipping_full_name,shipping_phone,shipping_address_line1,shipping_city,shipping_state,shipping_postal_code,shipping_country,
 expires_at,released_at,expired_at,consumed_at)
 VALUES(p_user,p_key,'synthetic-fingerprint',p_status,'USD',10,'Synthetic Customer','0000000000','Synthetic street','Synthetic city','Synthetic state','000000','India',now()+interval '45 minutes',
 CASE WHEN p_status='released' THEN now() END,CASE WHEN p_status='expired' THEN now() END,CASE WHEN p_status='consumed' THEN now() END) RETURNING id INTO result;
 RETURN result;
END $$;
INSERT INTO auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
SELECT ('18000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','checkout-'||n||'@example.test','',now(),'{}','{}',now(),now() FROM generate_series(1,3) n;
INSERT INTO public.profiles(id,username) SELECT ('18000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'checkout_'||n FROM generate_series(1,3) n;
INSERT INTO public.roles(id,code,name) VALUES('28000000-0000-4000-8000-000000000001','admin','Administrator') ON CONFLICT(code) DO NOTHING;
INSERT INTO public.user_roles(user_id,role_id) SELECT '18000000-0000-4000-8000-000000000003',id FROM public.roles WHERE code='admin';
CREATE TEMP TABLE inventory_before AS SELECT * FROM public.evo_store_inventory;
CREATE TEMP TABLE movements_before AS SELECT * FROM public.evo_store_inventory_movements;

SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001','88000000-0000-4000-8000-000000000001')$$,'valid active complete snapshot and unknown totals; 45-minute duration permitted');
SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000002','88000000-0000-4000-8000-000000000001')$$,'same key different user succeeds');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET released_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header released_at=now()');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET expired_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header expired_at=now()');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET consumed_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header consumed_at=now()');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='released' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header status=''released''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='expired' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header status=''expired''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='consumed' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header status=''consumed''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET subtotal=0 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header subtotal=0');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET subtotal=-1 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header subtotal=-1');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET subtotal='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header subtotal=''NaN''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET discount_total=-1 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header discount_total=-1');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET shipping_total=-1 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header shipping_total=-1');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET tax_total=-1 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header tax_total=-1');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET grand_total=-1 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header grand_total=-1');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET expires_at=created_at WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header expires_at=created_at');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET expires_at=created_at-interval '1 second' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header expires_at=created_at-interval ''1 second''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET request_fingerprint=E' \t\n' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header request_fingerprint=E'' \t\n''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='XYZ' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header currency=''XYZ''');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET shipping_full_name=' ' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject header shipping_full_name='' ''');
SELECT throws_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001')$$,'23505',NULL,'second active row fails');
SELECT throws_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001','88000000-0000-4000-8000-000000000001','released')$$,'23505',NULL,'duplicate user key fails across statuses');
SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001',gen_random_uuid(),'released')$$,'released consistent timestamps succeed');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='active',released_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='released'$$,'23514',NULL,'released cannot return to active');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='expired',expired_at=now(),released_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='released'$$,'23514',NULL,'released cannot change terminal state');
SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001',gen_random_uuid(),'expired')$$,'expired consistent timestamps succeed');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='active',expired_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='expired'$$,'23514',NULL,'expired cannot return to active');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='released',released_at=now(),expired_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='expired'$$,'23514',NULL,'expired cannot change terminal state');
SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001',gen_random_uuid(),'consumed')$$,'consumed consistent timestamps succeed');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='active',consumed_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='consumed'$$,'23514',NULL,'consumed cannot return to active');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='released',released_at=now(),consumed_at=NULL WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='consumed'$$,'23514',NULL,'consumed cannot change terminal state');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET status='released',released_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'active can release');
SELECT lives_ok($$SELECT pg_temp.checkout('18000000-0000-4000-8000-000000000001')$$,'terminal history plus new active succeeds');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='JPY',subtotal=10.5 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'fractional header JPY fails');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a WHERE p.oid='private.evo_store_currency_supported(text)'::regprocedure AND a.grantee=0),'PUBLIC cannot execute currency helper');
SELECT is((SELECT count(*)::integer FROM pg_depend d JOIN pg_constraint c ON c.oid=d.objid WHERE d.classid='pg_constraint'::regclass AND d.refclassid='pg_proc'::regclass AND d.refobjid='private.evo_store_currency_supported(text)'::regprocedure),3,'all three currency CHECKs track helper dependency');
SELECT throws_ok($$DROP FUNCTION private.evo_store_currency_supported(text)$$,'2BP01',NULL,'dropping shared helper requires explicit handling of dependent CHECKs');
SELECT ok((SELECT bool_and(private.evo_store_currency_supported(a||b||c) = ((a||b||c)::char(3) IN ('USD','EUR','GBP','INR','CAD','AUD','NZD','SGD','AED','JPY'))) FROM regexp_split_to_table('ABCDEFGHIJKLMNOPQRSTUVWXYZ','') a CROSS JOIN regexp_split_to_table('ABCDEFGHIJKLMNOPQRSTUVWXYZ','') b CROSS JOIN regexp_split_to_table('ABCDEFGHIJKLMNOPQRSTUVWXYZ','') c),'helper matches original price whitelist for all uppercase three-letter codes');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET shipping_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'shipping_total permits unknown');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET shipping_total=0 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'shipping_total permits zero');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET shipping_total=1.25 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'shipping_total permits positive two-decimal');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET shipping_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'shipping_total reset to unknown');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET tax_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'tax_total permits unknown');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET tax_total=0 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'tax_total permits zero');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET tax_total=1.25 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'tax_total permits positive two-decimal');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET tax_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'tax_total reset to unknown');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET grand_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'grand_total permits unknown');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET grand_total=0 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'grand_total permits zero');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET grand_total=1.25 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'grand_total permits positive two-decimal');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET grand_total=NULL WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'grand_total reset to unknown');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET subtotal='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'subtotal rejects numeric NaN');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET discount_total='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'discount_total rejects numeric NaN');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET shipping_total='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'shipping_total rejects numeric NaN');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET tax_total='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'tax_total rejects numeric NaN');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET grand_total='NaN' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'grand_total rejects numeric NaN');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET subtotal=10.25,discount_total=0.25 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'non-JPY header retains two decimal values');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET subtotal=10,discount_total=0 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'reset money fixture');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='JPY',discount_total=0.5 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'JPY discount_total rejects fractional value');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='JPY',shipping_total=0.5 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'JPY shipping_total rejects fractional value');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='JPY',tax_total=0.5 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'JPY tax_total rejects fractional value');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='JPY',grand_total=0.5 WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'JPY grand_total rejects fractional value');
SAVEPOINT lifecycle_transition;
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET status='expired',expired_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'trusted active can transition to expired');
ROLLBACK TO SAVEPOINT lifecycle_transition; RELEASE SAVEPOINT lifecycle_transition;
SAVEPOINT lifecycle_transition;
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET status='consumed',consumed_at=now() WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'trusted active can transition to consumed');
ROLLBACK TO SAVEPOINT lifecycle_transition; RELEASE SAVEPOINT lifecycle_transition;
INSERT INTO public.evo_store_products(id,name,slug,product_mode,base_price,currency)
 VALUES('48000000-0000-4000-8000-000000000001','Synthetic Product','checkout-synthetic','physical',10,'USD');
INSERT INTO public.evo_store_variants(id,product_id,sku,name,price,currency,size_code)
 SELECT ('58000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'48000000-0000-4000-8000-000000000001','CHECKOUT-'||n,NULL,10,'USD',n::text FROM generate_series(1,3) n;
CREATE FUNCTION pg_temp.item(p_checkout uuid,p_variant uuid,p_quantity integer DEFAULT 1,p_price numeric DEFAULT 10,p_total numeric DEFAULT 10,p_currency text DEFAULT 'USD')
RETURNS void LANGUAGE sql AS $$
 INSERT INTO public.evo_store_checkout_items(checkout_id,variant_id,product_id,quantity,currency,unit_price,line_subtotal,product_name,sku)
 VALUES(p_checkout,p_variant,'48000000-0000-4000-8000-000000000001',p_quantity,p_currency,p_price,p_total,'Synthetic Product','SYNTHETIC-SKU');
$$;

SELECT lives_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000001')$$,'quantity one and nullable variant name succeeds');
SELECT lives_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000002',10,10,100)$$,'quantity ten succeeds');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000001')$$,'23505',NULL,'duplicate variant rejected');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',0,10,10,'USD')$$,'23514',NULL,'invalid item 0/10/10/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',11,10,110,'USD')$$,'23514',NULL,'invalid item 11/10/110/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,0,10,'USD')$$,'23514',NULL,'invalid item 1/0/10/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,-1,10,'USD')$$,'23514',NULL,'invalid item 1/-1/10/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10,9,'USD')$$,'23514',NULL,'invalid item 1/10/9/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10,0,'USD')$$,'23514',NULL,'invalid item 1/10/0/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10,-1,'USD')$$,'23514',NULL,'invalid item 1/10/-1/USD');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10,10,'XYZ')$$,'23514',NULL,'invalid item 1/10/10/XYZ');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10.5,10.5,'JPY')$$,'23514',NULL,'invalid item 1/10.5/10.5/JPY');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',1,10,10,'EUR')$$,'23503',NULL,'supported but mismatched header currency rejected by FK');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET product_name=' ' WHERE checkout_id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject item product_name='' ''');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET sku=E'\t' WHERE checkout_id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject item sku=E''\t''');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET unit_price='NaN',line_subtotal='NaN' WHERE checkout_id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23514',NULL,'reject item unit_price=''NaN'',line_subtotal=''NaN''');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET currency='JPY' WHERE user_id='18000000-0000-4000-8000-000000000002'$$,'integral JPY header succeeds');
SELECT lives_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000002'),'58000000-0000-4000-8000-000000000001',1,10,10,'JPY')$$,'integral JPY item succeeds');
SELECT throws_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000002'),'58000000-0000-4000-8000-000000000002',2,10.5,21,'JPY')$$,'23514',NULL,'JPY fractional unit price rejected even when computed line subtotal is integral');
SAVEPOINT decimal_item;
SELECT lives_ok($$SELECT pg_temp.item((SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active'),'58000000-0000-4000-8000-000000000003',2,10.25,20.50,'USD')$$,'non-JPY two-decimal unit price and exact line arithmetic are valid');
ROLLBACK TO SAVEPOINT decimal_item;
RELEASE SAVEPOINT decimal_item;
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET currency='EUR' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23503',NULL,'header currency cannot diverge from items');
SAVEPOINT catalog_archival;
SELECT lives_ok($$UPDATE public.evo_store_variants SET is_active=false WHERE product_id='48000000-0000-4000-8000-000000000001'$$,'variant archival preserves history');
SELECT lives_ok($$UPDATE public.evo_store_products SET publication_status='archived' WHERE id='48000000-0000-4000-8000-000000000001'$$,'product archival preserves history');
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkout_items),3,'archival keeps all snapshot items');
SELECT ok((SELECT bool_and(product_name='Synthetic Product' AND sku='SYNTHETIC-SKU') FROM public.evo_store_checkout_items),'archival leaves presentation snapshots intact');
ROLLBACK TO SAVEPOINT catalog_archival;
RELEASE SAVEPOINT catalog_archival;
SELECT throws_ok($$DELETE FROM public.evo_store_variants WHERE id='58000000-0000-4000-8000-000000000001'$$,'23503',NULL,'variant deletion cannot erase snapshots');
SELECT throws_ok($$DELETE FROM public.evo_store_products WHERE id='48000000-0000-4000-8000-000000000001'$$,'23503',NULL,'catalog deletion cannot erase history');
SELECT throws_ok($$DELETE FROM public.evo_store_checkouts WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')$$,'23503',NULL,'checkout deletion cannot cascade items');
SELECT throws_ok($$DELETE FROM public.profiles WHERE id='18000000-0000-4000-8000-000000000001'$$,'23503',NULL,'profile deletion preserves checkouts');
INSERT INTO public.addresses(id,user_id,full_name,phone,address_line1,city,state,postal_code) VALUES('98000000-0000-4000-8000-000000000001','18000000-0000-4000-8000-000000000001','Saved','000','Saved street','Saved city','Saved state','000');
UPDATE public.evo_store_checkouts SET address_id='98000000-0000-4000-8000-000000000001' WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active');
UPDATE public.addresses SET full_name='Changed' WHERE id='98000000-0000-4000-8000-000000000001';
SELECT is((SELECT shipping_full_name FROM public.evo_store_checkouts WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')),'Synthetic Customer','address edits do not change snapshot');
SELECT lives_ok($$DELETE FROM public.addresses WHERE id='98000000-0000-4000-8000-000000000001'$$,'address deletion succeeds without destroying history');
SELECT ok((SELECT address_id IS NULL AND shipping_full_name='Synthetic Customer' FROM public.evo_store_checkouts WHERE id=(SELECT id FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001' AND status='active')),'address deletion only clears source reference');
INSERT INTO public.addresses(id,user_id,full_name,phone,address_line1,city,state,postal_code) VALUES('98000000-0000-4000-8000-000000000002','18000000-0000-4000-8000-000000000002','Other Customer','000','Other street','Other city','Other state','000');
SET LOCAL ROLE anon;
SELECT throws_ok($$SELECT * FROM public.evo_store_checkouts$$,'42501',NULL,'anonymous cannot read evo_store_checkouts');
SELECT throws_ok($$SELECT * FROM public.evo_store_checkout_items$$,'42501',NULL,'anonymous cannot read evo_store_checkout_items');
SELECT throws_ok($$INSERT INTO public.evo_store_checkouts(id) VALUES(gen_random_uuid())$$,'42501',NULL,'anonymous cannot insert evo_store_checkouts');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET id=id$$,'42501',NULL,'anonymous cannot update evo_store_checkouts');
SELECT throws_ok($$DELETE FROM public.evo_store_checkouts$$,'42501',NULL,'anonymous cannot delete evo_store_checkouts');
SELECT throws_ok($$INSERT INTO public.evo_store_checkout_items(id) VALUES(gen_random_uuid())$$,'42501',NULL,'anonymous cannot insert evo_store_checkout_items');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET id=id$$,'42501',NULL,'anonymous cannot update evo_store_checkout_items');
SELECT throws_ok($$DELETE FROM public.evo_store_checkout_items$$,'42501',NULL,'anonymous cannot delete evo_store_checkout_items');
RESET ROLE; SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000002'),0,'other customer headers hidden');
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkouts WHERE user_id='18000000-0000-4000-8000-000000000001'),5,'own active and terminal history visible');
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkout_items),2,'only own items visible');
SELECT throws_ok($$INSERT INTO public.evo_store_checkouts(id) VALUES(gen_random_uuid())$$,'42501',NULL,'customer cannot insert evo_store_checkouts');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET id=id$$,'42501',NULL,'customer cannot update evo_store_checkouts');
SELECT throws_ok($$DELETE FROM public.evo_store_checkouts$$,'42501',NULL,'customer cannot delete evo_store_checkouts');
SELECT throws_ok($$INSERT INTO public.evo_store_checkout_items(id) VALUES(gen_random_uuid())$$,'42501',NULL,'customer cannot insert evo_store_checkout_items');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET id=id$$,'42501',NULL,'customer cannot update evo_store_checkout_items');
SELECT throws_ok($$DELETE FROM public.evo_store_checkout_items$$,'42501',NULL,'customer cannot delete evo_store_checkout_items');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET address_id='98000000-0000-4000-8000-000000000002'$$,'42501',NULL,'customer cannot attach another users saved address through direct DML');
SELECT set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000003',true);
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkouts),6,'staff sees all checkout history');
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkout_items),3,'staff sees all items');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET id=id$$,'42501',NULL,'staff has no direct snapshot updates evo_store_checkouts');
SELECT throws_ok($$UPDATE public.evo_store_checkout_items SET id=id$$,'42501',NULL,'staff has no direct snapshot updates evo_store_checkout_items');
SELECT throws_ok($$INSERT INTO public.evo_store_checkouts(id) VALUES(gen_random_uuid())$$,'42501',NULL,'staff cannot directly insert evo_store_checkouts');
SELECT throws_ok($$DELETE FROM public.evo_store_checkouts$$,'42501',NULL,'staff cannot directly delete evo_store_checkouts');
SELECT throws_ok($$INSERT INTO public.evo_store_checkout_items(id) VALUES(gen_random_uuid())$$,'42501',NULL,'staff cannot directly insert evo_store_checkout_items');
SELECT throws_ok($$DELETE FROM public.evo_store_checkout_items$$,'42501',NULL,'staff cannot directly delete evo_store_checkout_items');
RESET ROLE; SET LOCAL ROLE service_role;
SELECT is((SELECT count(*)::integer FROM public.evo_store_checkouts),6,'service role can read checkout history');
SELECT lives_ok($$INSERT INTO public.evo_store_checkouts(id,user_id,idempotency_key,request_fingerprint,status,currency,subtotal,shipping_full_name,shipping_phone,shipping_address_line1,shipping_city,shipping_state,shipping_postal_code,shipping_country,expires_at,released_at) VALUES('a8000000-0000-4000-8000-000000000001','18000000-0000-4000-8000-000000000001',gen_random_uuid(),'service-fixture','released','USD',10,'Synthetic Service','000','Synthetic street','Synthetic city','Synthetic state','000','India',now()+interval '45 minutes',now())$$,'service role can insert complete checkout with currency CHECK');
SELECT lives_ok($$UPDATE public.evo_store_checkouts SET shipping_phone='001' WHERE id='a8000000-0000-4000-8000-000000000001'$$,'service role can repair snapshot without changing terminal state');
SELECT throws_ok($$UPDATE public.evo_store_checkouts SET status='active',released_at=NULL WHERE id='a8000000-0000-4000-8000-000000000001'$$,'23514',NULL,'service role cannot resurrect terminal reservation');
SELECT lives_ok($$INSERT INTO public.evo_store_checkout_items(id,checkout_id,variant_id,product_id,quantity,currency,unit_price,line_subtotal,product_name,sku) VALUES('b8000000-0000-4000-8000-000000000001','a8000000-0000-4000-8000-000000000001','58000000-0000-4000-8000-000000000003','48000000-0000-4000-8000-000000000001',1,'USD',10,10,'Synthetic Service','SERVICE-SYNTHETIC')$$,'service role can insert item with currency CHECK and FK');
SELECT lives_ok($$UPDATE public.evo_store_checkout_items SET unit_price=11,line_subtotal=11 WHERE id='b8000000-0000-4000-8000-000000000001'$$,'service role can update item consistently');
SELECT lives_ok($$DELETE FROM public.evo_store_checkout_items WHERE id='b8000000-0000-4000-8000-000000000001'$$,'service role can explicitly delete item');
SELECT lives_ok($$DELETE FROM public.evo_store_checkouts WHERE id='a8000000-0000-4000-8000-000000000001'$$,'service role can delete unreferenced checkout');
RESET ROLE;
SELECT ok(NOT EXISTS ((SELECT * FROM public.evo_store_inventory EXCEPT SELECT * FROM inventory_before) UNION ALL (SELECT * FROM inventory_before EXCEPT SELECT * FROM public.evo_store_inventory)),'evo_store_inventory unchanged by checkout fixture operations');
SELECT ok(NOT EXISTS ((SELECT * FROM public.evo_store_inventory_movements EXCEPT SELECT * FROM movements_before) UNION ALL (SELECT * FROM movements_before EXCEPT SELECT * FROM public.evo_store_inventory_movements)),'evo_store_inventory_movements unchanged by checkout fixture operations');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid IN ('public.evo_store_checkouts'::regclass,'public.evo_store_checkout_items'::regclass) AND NOT t.tgisinternal AND p.proname NOT IN ('set_updated_at','guard_evo_store_checkout_terminal_status')),'no reservation/inventory mutation triggers');
SELECT ok(to_regclass('public.evo_store_inventory_reservations') IS NULL,'evo_store_inventory_reservations not introduced');
SELECT ok(to_regclass('public.evo_store_inventory_reservation_items') IS NULL,'evo_store_inventory_reservation_items not introduced');
SELECT ok(to_regclass('public.evo_store_orders') IS NULL,'evo_store_orders not introduced');
SELECT ok(to_regclass('public.evo_store_order_items') IS NULL,'evo_store_order_items not introduced');
SELECT ok(to_regclass('public.evo_store_payments') IS NULL,'evo_store_payments not introduced');
SELECT * FROM finish();
ROLLBACK;
