import Link from 'next/link'
import { requireAdmin } from '@/lib/admin-auth'
import { getStoreAdminProducts } from '@/lib/admin-store'

export default async function StoreProductsPage() {
  await requireAdmin()
  const result = await getStoreAdminProducts()
  return <section aria-labelledby="store-products-title">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Evo Store · Catalog</p><h1 id="store-products-title" className="mt-3 text-3xl font-semibold sm:text-4xl">Products</h1><p className="mt-3 text-zinc-400">Manage product core records and publication lifecycle.</p></div><div className="flex gap-3"><Link href="/admin/store" className="button-secondary px-4 py-3 text-sm font-bold">Back to Evo Store</Link><Link href="/admin/store/products/new" className="button-primary px-4 py-3 text-sm">New Product</Link></div></div>
    {result.hasError ? <p role="alert" className="mt-8 border border-rose-400/30 p-5 text-rose-200">Products could not be loaded right now.</p> : result.products.length === 0 ? <p className="mt-8 border border-dashed border-white/15 p-8 text-center text-zinc-400">No Store products yet.</p> : <div className="mt-8 overflow-x-auto border border-white/10"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/10 bg-zinc-900/70 text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-5 py-4">Product</th><th className="px-5 py-4">Category</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Mode</th><th className="px-5 py-4">Featured</th><th className="px-5 py-4">Updated</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y divide-white/10">{result.products.map((product) => <tr key={product.id}><td className="px-5 py-4"><p className="font-semibold text-white">{product.name}</p><p className="text-zinc-500">/{product.slug}</p></td><td className="px-5 py-4 text-zinc-300">{product.category?.name ?? 'Unassigned'}</td><td className="px-5 py-4 uppercase text-zinc-300">{product.publication_status}</td><td className="px-5 py-4 capitalize text-zinc-300">{product.product_mode}</td><td className="px-5 py-4">{product.is_featured ? 'Yes' : 'No'}</td><td className="px-5 py-4 text-zinc-400"><time dateTime={product.updated_at}>{new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(product.updated_at))}</time></td><td className="px-5 py-4 text-right"><Link href={`/admin/store/products/${product.id}`} className="font-semibold text-amber-300">{product.publication_status === 'archived' ? 'View' : 'Edit'}</Link></td></tr>)}</tbody></table></div>}
  </section>
}
