import Link from 'next/link'
import { notFound } from 'next/navigation'

import { requireAdmin } from '@/lib/admin-auth'
import { getAdminReport, reportLabel, reportProfileName, REPORT_RESOLUTION_NOTE_MAX, ReportStatus } from '@/lib/admin-circle-reports'
import { removeDiscussion, removeReply, restoreDiscussion, restoreReply, setDiscussionLocked, setDiscussionPinned } from '../../discussions/actions'
import { dismissReport, markReportActionTaken, markReportReviewed } from '../actions'

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(value)) }
function statusClass(status: ReportStatus) { return status === 'pending' ? 'border-amber-300/40 text-amber-200' : status === 'reviewed' ? 'border-sky-300/40 text-sky-200' : status === 'dismissed' ? 'border-zinc-500 text-zinc-300' : 'border-emerald-400/40 text-emerald-200' }

export default async function CircleReportDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  await requireAdmin()
  const { id } = await params
  if (!UUID.test(id)) notFound()
  const [query, result] = await Promise.all([searchParams, getAdminReport(id)])
  if (!result.report && !result.hasError) notFound()
  if (!result.report) return <section><p role="alert" className="border border-rose-400/30 bg-rose-400/5 p-5 text-rose-200">This report could not be loaded right now.</p><Link href="/admin/circle/reports" className="button-secondary mt-5 px-4 py-3 text-sm font-bold">Back to reports</Link></section>
  const report = result.report
  const dispositionActions = report.status === 'pending' ? [
    { label: 'Mark reviewed', action: markReportReviewed, style: 'button-secondary' },
    { label: 'Dismiss report', action: dismissReport, style: 'button-secondary' },
    { label: 'Mark action taken', action: markReportActionTaken, style: 'button-primary' },
  ] : report.status === 'reviewed' ? [{ label: 'Update review note', action: markReportReviewed, style: 'button-primary' }] : report.status === 'dismissed' ? [{ label: 'Update dismissal note', action: dismissReport, style: 'button-primary' }] : [{ label: 'Update action note', action: markReportActionTaken, style: 'button-primary' }]

  return <article aria-labelledby="report-title">
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Evo Circle · Report review</p><h1 id="report-title" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{reportLabel(report.content_type)} report</h1><p className="mt-2 break-all text-sm text-zinc-500">Report {report.id}</p></div><Link href="/admin/circle/reports" className="button-secondary px-4 py-3 text-sm font-bold">Back to reports</Link></div>
    {query.success ? <p role="status" className="mt-6 border border-emerald-400/30 bg-emerald-400/5 p-4 text-emerald-200">Report disposition and review note saved.</p> : null}
    {query.error ? <p role="alert" className="mt-6 border border-rose-400/30 bg-rose-400/5 p-4 text-rose-200">{query.error === 'transition' ? 'That disposition transition is not allowed. Refresh and try again.' : query.error === 'note' ? `Resolution notes must be ${REPORT_RESOLUTION_NOTE_MAX.toLocaleString('en')} characters or fewer.` : 'The requested update could not be completed. Please try again.'}</p> : null}
    {result.hasError ? <p role="alert" className="mt-6 border border-amber-300/30 bg-amber-300/5 p-4 text-amber-100">Some target or identity context could not be loaded.</p> : null}

    <div className="mt-7 grid gap-6 lg:grid-cols-2">
      <section className="border border-white/10 bg-zinc-900/40 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Report</h2><span className={`border px-2.5 py-1 text-xs font-bold uppercase ${statusClass(report.status)}`}>{reportLabel(report.status)}</span></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Reason</dt><dd className="mt-1 text-zinc-200">{reportLabel(report.reason)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Content type</dt><dd className="mt-1 text-zinc-200">{reportLabel(report.content_type)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Submitted</dt><dd className="mt-1 text-zinc-200">{formatDate(report.created_at)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Full details</dt><dd className="mt-2 whitespace-pre-wrap break-words leading-7 text-zinc-300">{report.details || 'No additional details supplied.'}</dd></div></dl></section>
      <section className="border border-white/10 bg-zinc-900/40 p-5 sm:p-7"><h2 className="text-xl font-semibold">Reporter &amp; review</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Reporter</dt><dd className="mt-1 text-zinc-200">{reportProfileName(report.reporter)}{report.reporter?.username && report.reporter.display_name ? <span className="ml-2 text-zinc-500">@{report.reporter.username}</span> : null}</dd><dd className="mt-1 break-all text-xs text-zinc-600">ID: {report.reporter_id}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Reviewed by</dt><dd className="mt-1 text-zinc-200">{report.reviewed_by ? reportProfileName(report.reviewer) : 'Not reviewed yet'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Reviewed at</dt><dd className="mt-1 text-zinc-200">{report.reviewed_at ? formatDate(report.reviewed_at) : '—'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-zinc-500">Resolution note</dt><dd className="mt-1 whitespace-pre-wrap break-words leading-6 text-zinc-300">{report.resolution_note || 'No resolution note.'}</dd></div></dl></section>
    </div>

    <section aria-labelledby="target-heading" className="mt-6 border border-white/10 bg-zinc-950/40 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">Target context</p><h2 id="target-heading" className="mt-2 text-2xl font-semibold">Reported {reportLabel(report.content_type)}</h2></div><span className={`border px-2.5 py-1 text-xs font-bold uppercase ${report.target.available ? 'border-white/20 text-zinc-200' : 'border-rose-400/30 text-rose-200'}`}>{report.target.available ? `Target: ${reportLabel(report.target.status)}` : 'Target unavailable'}</span></div>
      {report.discussion ? <div className="mt-6"><h3 className="text-xl font-semibold">{report.discussion.title}</h3><p className="mt-2 text-sm text-zinc-400">By {reportProfileName(report.discussion.author)} · {formatDate(report.discussion.created_at)} · updated {formatDate(report.discussion.updated_at)}</p><div className="mt-3 flex flex-wrap gap-2 text-xs uppercase"><span className="border border-white/15 px-2 py-1">{report.discussion.status}</span><span className="border border-white/15 px-2 py-1">{report.discussion.locked ? 'Replies locked' : 'Replies open'}</span><span className="border border-white/15 px-2 py-1">{report.discussion.pinned ? 'Pinned' : 'Not pinned'}</span></div><p className="mt-5 whitespace-pre-wrap break-words text-sm leading-7 text-zinc-300">{report.discussion.body}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/admin/circle/discussions/${report.discussion.id}`} className="button-secondary px-4 py-2.5 text-sm font-bold">Open discussion review</Link><form action={setDiscussionPinned.bind(null, report.discussion.id, !report.discussion.pinned)}><button className="button-secondary px-4 py-2.5 text-sm font-bold">{report.discussion.pinned ? 'Unpin discussion' : 'Pin discussion'}</button></form>{report.discussion.status === 'published' ? <><form action={setDiscussionLocked.bind(null, report.discussion.id, !report.discussion.locked)}><button className="button-secondary px-4 py-2.5 text-sm font-bold">{report.discussion.locked ? 'Unlock replies' : 'Lock replies'}</button></form><form action={removeDiscussion.bind(null, report.discussion.id)}><button className="button-danger px-4 py-2.5 text-sm">Remove discussion</button></form></> : report.discussion.status === 'removed' ? <form action={restoreDiscussion.bind(null, report.discussion.id)}><button className="button-primary px-4 py-2.5 text-sm">Restore discussion</button></form> : null}</div></div> : null}
      {report.reply ? <div className="mt-6"><p className="text-sm text-zinc-400">Reply by {reportProfileName(report.reply.author)} · {formatDate(report.reply.created_at)} · updated {formatDate(report.reply.updated_at)}</p><p className="mt-4 whitespace-pre-wrap break-words border-l-2 border-amber-300/40 pl-4 text-sm leading-7 text-zinc-200">{report.reply.body}</p>{report.reply.parent ? <div className="mt-5 border border-white/10 bg-zinc-900/50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">Parent reply · {reportLabel(report.reply.parent.status)} · {reportProfileName(report.reply.parent.author)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-zinc-400">{report.reply.parent.body}</p></div> : null}{report.owningDiscussion ? <div className="mt-5"><p className="font-semibold">Discussion: {report.owningDiscussion.title}</p><p className="mt-1 text-sm text-zinc-400">{reportLabel(report.owningDiscussion.status)} · {report.owningDiscussion.locked ? 'Replies locked' : 'Replies open'}</p><div className="mt-4 flex flex-wrap gap-3"><Link href={`/admin/circle/discussions/${report.owningDiscussion.id}#reply-${report.reply.id}`} className="button-secondary px-4 py-2.5 text-sm font-bold">Open reply in discussion</Link>{report.reply.status === 'published' ? <form action={removeReply.bind(null, report.owningDiscussion.id, report.reply.id)}><button className="button-danger px-4 py-2.5 text-sm">Remove reply</button></form> : <form action={restoreReply.bind(null, report.owningDiscussion.id, report.reply.id)}><button className="button-primary px-4 py-2.5 text-sm">Restore reply</button></form>}</div></div> : <p className="mt-5 text-rose-200">The owning discussion is unavailable, so no reply action is offered.</p>}</div> : null}
      {!report.discussion && !report.reply ? <div className="mt-6"><p className="font-semibold text-white">{report.target.title || `${reportLabel(report.content_type)} target`}</p><p className="mt-2 text-zinc-400">{report.target.available ? `Current status: ${reportLabel(report.target.status)}.` : 'The target could not be loaded.'} Article and Evo TV moderation actions are intentionally outside Circle V1.</p></div> : null}
    </section>

    <section aria-labelledby="disposition-heading" className="mt-6 border border-amber-300/20 bg-amber-300/[0.03] p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">Separate workflow</p><h2 id="disposition-heading" className="mt-2 text-xl font-semibold">Report disposition</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">Content moderation above does not change this report. Record the report outcome explicitly here.</p><form action={dispositionActions[0].action.bind(null, report.id)} className="mt-5"><label htmlFor="resolution_note" className="text-xs font-bold uppercase tracking-wider text-zinc-400">Resolution note <span className="normal-case text-zinc-600">(optional)</span></label><textarea id="resolution_note" name="resolution_note" maxLength={REPORT_RESOLUTION_NOTE_MAX} rows={5} defaultValue={report.resolution_note ?? ''} className="mt-2 w-full border border-white/15 bg-black/40 px-3 py-3 text-sm text-white outline-none focus:border-amber-300" /><div className="mt-4 flex flex-wrap gap-3">{dispositionActions.map((item, index) => index === 0 ? <button key={item.label} className={`${item.style} px-4 py-2.5 text-sm font-bold`}>{item.label}</button> : <button key={item.label} formAction={item.action.bind(null, report.id)} className={`${item.style} px-4 py-2.5 text-sm font-bold`}>{item.label}</button>)}</div></form></section>
  </article>
}
